### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by komais** [StoreyLab/subSeq#4]
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  namespace ‘qvalue’ 1.40.0 is being loaded, but >= 1.99 is required

but i only find qvalue 1.40.0 in biocondctor , so where can i download > 1.99?

**Comment by dgrtwo** [comment]
As noted [here](https://github.com/StoreyLab/subSeq#installation), please install this first:

    install_github("jdstorey/qvalue")
