### ISSUE TITLE
Program runs but # significant genes appears too high

### ISSUE THREAD

**Issue by ericavt** [StoreyLab/subSeq#5]
Hi there,
I can successfully run subSeq, and all looks good, except that the # of significant 'genes' detected DE seems far too high.
I have a dataset of raw unnormalised counts, with two conditions and three replicates each. We are mapping to a de novo transcriptome, and therefore have a large number of transcript contigs (n = 106,059 after filtering those with counts below 5 across all samples).

The subsamples.summary table looks as it should, expect for the number of significant genes is very high - 70,000-90,000 significant for the full dataset. We expect more like <30,000 DE genes between treatments based on our other analyses. At least with Voomlimma, the pattern is as expected for power - with a sharp increase then a plateau at a depth corresponding to what will be 10-20 million reads per sample.
Our commands are below. Any thoughts on where we might have gone wrong with the code, or why subSeq might be returning so may significant genes here? Thanks kindly in advance.

We run:
> library(subSeq)
> MvFgonad_raw <- read.table("bluehead_male_female_raw_counts.gonad.txt", sep="\t", header=TRUE)
> MvFgonad_raw5 = MvFgonad_raw[rowSums(MvFgonad_raw) >=5, ]
> View(MvFgonad_raw5)
> proportions=c(0.05,0.1,0.2,0.5,0.75,0.1)
> subsamples = subsample(MvFgonad_raw5, proportions, method = c("edgeR", "DESeq2", "voomLimma"), treatment=c("female", "female", "female", "male", "male", "male"))
> subsamples.summary=summary(subsamples)
> View(subsamples.summary)
> plot(subsamples.summary)

And the plot:
![rplot_mvfgonad_raw5_subsamples summary](https://cloud.githubusercontent.com/assets/11433955/6612008/1342c11a-c8d9-11e4-8c69-2a850db9fe4d.jpeg)

**Comment by dgrtwo** [comment]
That's odd, I can't see anything wrong with your code. Would you be willing to send me the `bluehead_male_female_raw_counts.gonad.txt`, at dgrtwo [at] princeton [dot] edu, so that I could reproduce the issue and find my bug? (I would of course delete it afterwards).

Thanks for using subSeq and for letting me know about the issue!
